"""updated password type

Revision ID: 7159582a0586
Revises: e01635569a14
Create Date: 2025-01-07 18:36:05.207292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7159582a0586'
down_revision: Union[str, None] = 'e01635569a14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'password',
        type_=sa.String(255),
        nullable=False,
        existing_type=sa.String(120),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'password',
        type_=sa.String(255),
        nullable=False,
        existing_type=sa.String(255),
    )
    # ### end Alembic commands ###
